apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: lee
  labels:
    name: my-pod
    app: my-app
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: http
